export const CENTERS: Library.CenterItem[] = [
  {
    centerId: 1,
    name: 'Centre for Public Policy & Governance (CPPG)',
    code: 'CPPG',
    advisorName: 'Dr. R. K. Sharma',
    location: 'Block A, 2nd Floor',
    isActive: true,
  },
  {
    centerId: 2,
    name: 'Centre for Urban Governance (CUG)',
    code: 'CUG',
    advisorName: 'Prof. Ananya Sen',
    location: 'Block A, 1st Floor',
    isActive: true,
  },
  {
    centerId: 3,
    name: 'Centre for Rural Development & Local Self Government (CRD)',
    code: 'CRD',
    advisorName: 'Dr. Vivek Mishra',
    location: 'Block B, Ground Floor',
    isActive: true,
  },
  {
    centerId: 4,
    name: 'Centre for Knowledge Management (CKM)',
    code: 'CKM',
    advisorName: 'Smt. Neeta Verma',
    location: 'Library Wing, 1st Floor',
    isActive: true,
  },
  {
    centerId: 5,
    name: 'Centre for Climate Change & Environment (CCE)',
    code: 'CCE',
    advisorName: 'Dr. Shweta Pathak',
    location: 'Block B, 2nd Floor',
    isActive: true,
  },
  {
    centerId: 6,
    name: 'Centre for Social Development & Inclusive Growth (CSD)',
    code: 'CSD',
    advisorName: 'Dr. Pradeep Nair',
    location: 'Block C, 1st Floor',
    isActive: true,
  },
  {
    centerId: 7,
    name: 'Centre for Financial Management & Policy (CFM)',
    code: 'CFM',
    advisorName: 'Shri Manoj Joshi',
    location: 'Block A, 3rd Floor',
    isActive: true,
  },
  {
    centerId: 8,
    name: 'Centre for Innovation & Emerging Technologies (CIET)',
    code: 'CIET',
    advisorName: 'Dr. Rajesh Patel',
    location: 'Block C, Ground Floor',
    isActive: true,
  },
  {
    centerId: 9,
    name: 'Centre for Human Resource & Capacity Building (CHRCB)',
    code: 'CHRCB',
    advisorName: 'Dr. Meenakshi Tiwari',
    location: 'Block B, 3rd Floor',
    isActive: true,
  },
];
