export const STATIC_BOOKS: Library.BookItem[] = [
  {
    bookId: 101,
    title: 'Good Governance: Delivering on Commitments',
    subTitle: 'A Blueprint for Public Service Delivery and Administrative Efficiency',
    author: 'Bimal Jalan',
    authors: ['Bimal Jalan', 'Dr. Subir Gokarn'],
    edition: '2nd Revised Edition',
    publication: 'Rupa Publications',
    year: 2021,
    numberOfCopies: 12,
    availableCopies: 9,
    categoryId: 1,
    categoryName: 'Centers Collection (9 Centers)',
    categoryType: 'CENTER',
    centerId: 1,
    centerName: 'Centre for Public Policy & Governance (CPPG)',
    isbn: '978-8129135001',
    shelfLocation: 'Rack A1-04',
    isActive: true,
  },
  {
    bookId: 102,
    title: 'Urban Dynamics and Municipal Finance in India',
    subTitle: 'Institutional Frameworks, Resource Mobilization & Municipal Bonds',
    author: 'Om Prakash Mathur',
    authors: ['Om Prakash Mathur', 'Dr. Alok Sharma'],
    edition: '1st Edition',
    publication: 'Oxford University Press',
    year: 2020,
    numberOfCopies: 8,
    availableCopies: 6,
    categoryId: 1,
    categoryName: 'Centers Collection (9 Centers)',
    categoryType: 'CENTER',
    centerId: 2,
    centerName: 'Centre for Urban Governance (CUG)',
    isbn: '978-0199498214',
    shelfLocation: 'Rack B2-11',
    isActive: true,
  },
  {
    bookId: 103,
    title: 'Transforming Rural India: Policies and Outcomes',
    author: 'K. P. Kannan & M. S. Swaminathan',
    publication: 'Academic Foundation',
    year: 2019,
    numberOfCopies: 10,
    availableCopies: 7,
    categoryId: 1,
    categoryName: 'Centers Collection (9 Centers)',
    categoryType: 'CENTER',
    centerId: 3,
    centerName: 'Centre for Rural Development & Local Self Government (CRD)',
    isbn: '978-9332704503',
    shelfLocation: 'Rack C1-02',
    isActive: true,
  },
  {
    bookId: 104,
    title: 'Knowledge Management in Public Administration',
    author: 'David E. McNabb',
    publication: 'Routledge',
    year: 2022,
    numberOfCopies: 6,
    availableCopies: 5,
    categoryId: 1,
    categoryName: 'Centers Collection (9 Centers)',
    categoryType: 'CENTER',
    centerId: 4,
    centerName: 'Centre for Knowledge Management (CKM)',
    isbn: '978-0765619983',
    shelfLocation: 'Rack D3-08',
    isActive: true,
  },
  {
    bookId: 105,
    title: 'Climate Adaptation Strategies for Central India',
    author: 'Sunita Narain & J. Shukla',
    publication: 'CSE Books',
    year: 2023,
    numberOfCopies: 15,
    availableCopies: 11,
    categoryId: 1,
    categoryName: 'Centers Collection (9 Centers)',
    categoryType: 'CENTER',
    centerId: 5,
    centerName: 'Centre for Climate Change & Environment (CCE)',
    isbn: '978-8186906231',
    shelfLocation: 'Rack E1-05',
    isActive: true,
  },
  {
    bookId: 106,
    title: 'Wings of Fire: An Autobiography',
    author: 'Dr. A. P. J. Abdul Kalam',
    publication: 'Universities Press',
    year: 2018,
    numberOfCopies: 25,
    availableCopies: 18,
    categoryId: 3,
    categoryName: 'Auto-Biographies & Biographies',
    categoryType: 'AUTOBIOGRAPHY',
    isbn: '978-8173711466',
    shelfLocation: 'Rack G2-14',
    isActive: true,
  },
  {
    bookId: 107,
    title: 'The Story of My Experiments with Truth',
    author: 'Mahatma Gandhi',
    publication: 'Navajivan Publishing House',
    year: 2017,
    numberOfCopies: 30,
    availableCopies: 22,
    categoryId: 3,
    categoryName: 'Auto-Biographies & Biographies',
    categoryType: 'AUTOBIOGRAPHY',
    isbn: '978-8172290085',
    shelfLocation: 'Rack G2-15',
    isActive: true,
  },
  {
    bookId: 108,
    title: 'Atomic Habits: Tiny Changes, Remarkable Results',
    author: 'James Clear',
    publication: 'Random House Business Books',
    year: 2021,
    numberOfCopies: 20,
    availableCopies: 14,
    categoryId: 2,
    categoryName: 'Motivational Books',
    categoryType: 'MOTIVATIONAL',
    isbn: '978-1847941831',
    shelfLocation: 'Rack M1-01',
    isActive: true,
  },
  {
    bookId: 109,
    title: 'Leading with Soul and Wisdom',
    author: 'Lee G. Bolman & Terrence E. Deal',
    publication: 'Jossey-Bass',
    year: 2020,
    numberOfCopies: 14,
    availableCopies: 12,
    categoryId: 2,
    categoryName: 'Motivational Books',
    categoryType: 'MOTIVATIONAL',
    isbn: '978-0470619001',
    shelfLocation: 'Rack M1-05',
    isActive: true,
  },
  {
    bookId: 110,
    title: 'Public Financial Systems and Direct Benefit Transfers',
    author: 'R. Gopalan & M. C. Singhi',
    publication: 'Sage Publications',
    year: 2022,
    numberOfCopies: 9,
    availableCopies: 7,
    categoryId: 1,
    categoryName: 'Centers Collection (9 Centers)',
    categoryType: 'CENTER',
    centerId: 7,
    centerName: 'Centre for Financial Management & Policy (CFM)',
    isbn: '978-9354790119',
    shelfLocation: 'Rack F1-03',
    isActive: true,
  },
  {
    bookId: 111,
    title: 'AI and Digital Governance in Indian States',
    author: 'Nandan Nilekani & Tanuj Bhojwani',
    publication: 'Penguin Enterprise',
    year: 2023,
    numberOfCopies: 16,
    availableCopies: 10,
    categoryId: 1,
    categoryName: 'Centers Collection (9 Centers)',
    categoryType: 'CENTER',
    centerId: 8,
    centerName: 'Centre for Innovation & Emerging Technologies (CIET)',
    isbn: '978-0670097616',
    shelfLocation: 'Rack I2-09',
    isActive: true,
  },
  {
    bookId: 112,
    title: 'Capacity Building Framework for Civil Services',
    author: 'Mission Karmayogi Research Cell',
    publication: 'AIGGPA Press',
    year: 2024,
    numberOfCopies: 18,
    availableCopies: 15,
    categoryId: 1,
    categoryName: 'Centers Collection (9 Centers)',
    categoryType: 'CENTER',
    centerId: 9,
    centerName: 'Centre for Human Resource & Capacity Building (CHRCB)',
    isbn: '978-9380001099',
    shelfLocation: 'Rack H1-07',
    isActive: true,
  },
  {
    bookId: 113,
    title: 'CM Helpline Citizen Satisfaction & Redressal Audit Report',
    author: 'Dr. R. K. Sharma (Advisor)',
    publication: 'AIGGPA Publications',
    year: 2024,
    numberOfCopies: 15,
    availableCopies: 11,
    categoryId: 4,
    categoryName: 'AIGGPA Center Reports (9 Centers Table)',
    categoryType: 'AIGGPA_REPORT',
    centerId: 1,
    centerName: 'Centre for Public Policy & Governance (CPPG)',
    advisor: 'Dr. R. K. Sharma',
    shelfLocation: 'Report Section R1',
    isActive: true,
  },
  {
    bookId: 114,
    title: 'Madhya Pradesh Economic Survey 2023-24',
    author: 'Directorate of Economics and Statistics, MP',
    publication: 'Government of Madhya Pradesh',
    department: 'Directorate of Economics & Statistics, MP',
    year: 2024,
    numberOfCopies: 25,
    availableCopies: 21,
    categoryId: 5,
    categoryName: 'External Dept. Reports (Kisi Bahar ke Dept. Ki Report)',
    categoryType: 'GENERAL_REPORT',
    shelfLocation: 'Govt Whitepaper Section G4',
    isActive: true,
  },
];

export const STATIC_AIGGPA_REPORTS: Library.AiggpaReportItem[] = [
  {
    reportId: 201,
    centerId: 1,
    centerName: 'Centre for Public Policy & Governance (CPPG)',
    advisor: 'Dr. R. K. Sharma',
    projectName: 'CM Helpline Citizen Satisfaction & Redressal Audit Report',
    year: 2024,
    numberOfCopies: 15,
    availableCopies: 11,
    documentUrl: '/docs/reports/cm-helpline-2024.pdf',
    isActive: true,
  },
  {
    reportId: 202,
    centerId: 2,
    centerName: 'Centre for Urban Governance (CUG)',
    advisor: 'Prof. Ananya Sen',
    projectName: 'Smart Cities Mission: Urban Mobility & Infrastructure Index in MP',
    year: 2023,
    numberOfCopies: 10,
    availableCopies: 8,
    documentUrl: '/docs/reports/smart-cities-mp-2023.pdf',
    isActive: true,
  },
  {
    reportId: 203,
    centerId: 3,
    centerName: 'Centre for Rural Development & Local Self Government (CRD)',
    advisor: 'Dr. Vivek Mishra',
    projectName: 'Panchayat Governance & Resource Mobilization Case Study',
    year: 2023,
    numberOfCopies: 12,
    availableCopies: 9,
    documentUrl: '/docs/reports/panchayat-governance-2023.pdf',
    isActive: true,
  },
  {
    reportId: 204,
    centerId: 4,
    centerName: 'Centre for Knowledge Management (CKM)',
    advisor: 'Smt. Neeta Sharma',
    projectName: 'AIGGPA Institutional Knowledge Repository Framework',
    year: 2024,
    numberOfCopies: 8,
    availableCopies: 7,
    documentUrl: '/docs/reports/ckm-framework-2024.pdf',
    isActive: true,
  },
  {
    reportId: 205,
    centerId: 5,
    centerName: 'Centre for Climate Change & Environment (CCE)',
    advisor: 'Dr. Shweta Pathak',
    projectName: 'State Climate Action Plan: Forest & Water Body Conservation',
    year: 2022,
    numberOfCopies: 14,
    availableCopies: 10,
    documentUrl: '/docs/reports/climate-action-2022.pdf',
    isActive: true,
  },
  {
    reportId: 206,
    centerId: 6,
    centerName: 'Centre for Social Development & Inclusive Growth (CSD)',
    advisor: 'Dr. Pradeep Nair',
    projectName: 'Tribal Livelihood and Forest Rights Implementation Study in MP',
    year: 2023,
    numberOfCopies: 12,
    availableCopies: 10,
    documentUrl: '/docs/reports/tribal-rights-2023.pdf',
    isActive: true,
  },
];

export const STATIC_GENERAL_REPORTS: Library.GeneralReportItem[] = [
  {
    reportId: 301,
    title: 'Madhya Pradesh Economic Survey 2023-24',
    category: 'Finance',
    subCategory: 'State Budgetary Analysis',
    year: 2024,
    numberOfCopies: 25,
    availableCopies: 21,
    author: 'Directorate of Economics and Statistics, MP',
    publisher: 'Government of Madhya Pradesh',
    isActive: true,
  },
  {
    reportId: 302,
    title: 'NITI Aayog Sustainable Development Goals (SDG) India Index 2023',
    category: 'Research',
    subCategory: 'Development Index Metrics',
    year: 2023,
    numberOfCopies: 15,
    availableCopies: 12,
    author: 'NITI Aayog',
    publisher: 'Government of India',
    isActive: true,
  },
  {
    reportId: 303,
    title: 'National Family Health Survey (NFHS-5) MP State Report',
    category: 'Medical',
    subCategory: 'Public Health Statistics',
    year: 2022,
    numberOfCopies: 20,
    availableCopies: 17,
    author: 'Ministry of Health & Family Welfare',
    publisher: 'IIPS Mumbai',
    isActive: true,
  },
  {
    reportId: 304,
    title: 'Reserve Bank of India: State Finances Study of Budgets 2023',
    category: 'Finance',
    subCategory: 'Monetary & Fiscal Study',
    year: 2023,
    numberOfCopies: 10,
    availableCopies: 9,
    author: 'Department of Economic and Policy Research, RBI',
    publisher: 'RBI Publications',
    isActive: true,
  },
];

export const STATIC_BORROW_RECORDS: Library.BorrowItem[] = [
  {
    borrowId: 1,
    bookId: 101,
    bookTitle: 'Good Governance: Delivering on Commitments',
    borrowerName: 'Amitabh Srivastava',
    centerOrSection: 'Centre for Public Policy & Governance (CPPG)',
    designation: 'Research Associate',
    issueDate: '2026-09-01',
    dueDate: '2026-10-01',
    returnDate: null,
    specialPermission: false,
    permissionGivenBy: '',
    status: 'ISSUED',
    reissueCount: 0,
    notes: 'For ongoing governance evaluation paper',
  },
  {
    borrowId: 2,
    bookId: 106,
    bookTitle: 'Wings of Fire: An Autobiography',
    borrowerName: 'Priyanka Sen',
    centerOrSection: 'Publications Section',
    designation: 'Documentation Officer',
    issueDate: '2026-08-15',
    dueDate: '2026-09-14',
    returnDate: null,
    specialPermission: false,
    permissionGivenBy: '',
    status: 'OVERDUE',
    reissueCount: 0,
    notes: 'Reminder sent via email',
  },
  {
    borrowId: 3,
    bookId: 102,
    bookTitle: 'Urban Dynamics and Municipal Finance in India',
    borrowerName: 'Deepak Chawla',
    centerOrSection: 'Centre for Urban Governance (CUG)',
    designation: 'Senior Consultant',
    issueDate: '2026-08-20',
    dueDate: '2026-09-19',
    returnDate: null,
    specialPermission: true,
    permissionGivenBy: 'Dr. Neeta Sharma (Section Head)',
    status: 'OVERDUE',
    reissueCount: 1,
    notes: 'Reissued once on 19 Aug with special advisor permission',
  },
  {
    borrowId: 4,
    bookId: 108,
    bookTitle: 'Atomic Habits: Tiny Changes, Remarkable Results',
    borrowerName: 'Rohit Agrawal',
    centerOrSection: 'Centre for Knowledge Management (CKM)',
    designation: 'Systems Analyst',
    issueDate: '2026-09-10',
    dueDate: '2026-10-10',
    returnDate: null,
    specialPermission: false,
    permissionGivenBy: '',
    status: 'ISSUED',
    reissueCount: 0,
    notes: '',
  },
  {
    borrowId: 5,
    bookId: 105,
    bookTitle: 'Climate Adaptation Strategies for Central India',
    borrowerName: 'Dr. Sunita Baghel',
    centerOrSection: 'Centre for Climate Change & Environment (CCE)',
    designation: 'Research Fellow',
    issueDate: '2026-07-10',
    dueDate: '2026-08-09',
    returnDate: '2026-08-05',
    specialPermission: false,
    permissionGivenBy: '',
    status: 'RETURNED',
    reissueCount: 0,
    notes: 'Returned in good condition',
  },
];

// ─── EXTENDED BORROWER PROFILE DETAILS (Joining Date, Contract End Date) ───
export const BORROWER_PROFILES: Record<string, { joiningDate: string; contractEndDate: string; designation: string; center: string }> = {
  'Amitabh Srivastava': {
    joiningDate: '2023-06-15',
    contractEndDate: '2027-06-14',
    designation: 'Research Associate',
    center: 'Centre for Public Policy & Governance (CPPG)',
  },
  'Deepak Chawla': {
    joiningDate: '2022-11-01',
    contractEndDate: '2026-10-31',
    designation: 'Senior Consultant',
    center: 'Centre for Urban Governance (CUG)',
  },
  'Rohit Agrawal': {
    joiningDate: '2024-01-10',
    contractEndDate: '2028-01-09',
    designation: 'Systems Analyst',
    center: 'Centre for Knowledge Management (CKM)',
  },
  'Dr. Sunita Baghel': {
    joiningDate: '2021-08-20',
    contractEndDate: '2026-08-19',
    designation: 'Research Fellow',
    center: 'Centre for Climate Change & Environment (CCE)',
  },
  'Priyanka Sen': {
    joiningDate: '2023-02-01',
    contractEndDate: '2027-01-31',
    designation: 'Documentation Officer',
    center: 'Publications Section',
  },
};

// ─── STATIC NEWSPAPERS ───
export const STATIC_NEWSPAPERS: Library.NewspaperItem[] = [
  {
    newspaperId: 1,
    name: 'Dainik Bhaskar',
    publicationType: 'NEWSPAPER',
    publisher: 'DB Corp Ltd',
    vendor: 'Bhopal News Agency Pvt Ltd',
    language: 'Hindi',
    frequency: 'Daily',
    subscriptionFrom: '2026-01-01',
    subscriptionTo: '2026-12-31',
    subscriptionAmount: 2400,
    financialYear: '2026-27',
    isActive: true,
  },
  {
    newspaperId: 2,
    name: 'The Hindu',
    publicationType: 'NEWSPAPER',
    publisher: 'Kasturi & Sons Ltd',
    vendor: 'Central India News Distributors',
    language: 'English',
    frequency: 'Daily',
    subscriptionFrom: '2026-01-01',
    subscriptionTo: '2026-12-31',
    subscriptionAmount: 4200,
    financialYear: '2026-27',
    isActive: true,
  },
  {
    newspaperId: 3,
    name: 'Hindustan Times',
    publicationType: 'NEWSPAPER',
    publisher: 'HT Media Ltd',
    vendor: 'National Periodical Supply Co.',
    language: 'English',
    frequency: 'Daily',
    subscriptionFrom: '2026-04-01',
    subscriptionTo: '2027-03-31',
    subscriptionAmount: 3800,
    financialYear: '2026-27',
    isActive: true,
  },
  {
    newspaperId: 7,
    name: 'Navbharat Times',
    publicationType: 'NEWSPAPER',
    publisher: 'Bennett Coleman & Co.',
    vendor: 'Times Group Circulation Division',
    language: 'Hindi',
    frequency: 'Daily',
    subscriptionFrom: '2025-01-01',
    subscriptionTo: '2025-12-31',
    subscriptionAmount: 2200,
    financialYear: '2025-26',
    isActive: false, // EXPIRED
    notes: 'Subscription expired — renewal pending',
  },
];

// ─── STATIC MAGAZINES ───
export const STATIC_MAGAZINES: Library.NewspaperItem[] = [
  {
    newspaperId: 101,
    name: 'India Today',
    publicationType: 'MAGAZINE',
    publisher: 'Living Media India Ltd',
    vendor: 'Thomson Press India Distribution',
    language: 'English',
    frequency: 'Weekly',
    subscriptionFrom: '2026-03-01',
    subscriptionTo: '2027-02-28',
    subscriptionAmount: 3500,
    financialYear: '2026-27',
    isActive: true,
  },
  {
    newspaperId: 102,
    name: 'Yojana',
    publicationType: 'MAGAZINE',
    publisher: 'Publications Division, Ministry of I&B',
    vendor: 'Government Publications Sales Depot',
    language: 'Hindi / English',
    frequency: 'Monthly',
    subscriptionFrom: '2026-04-01',
    subscriptionTo: '2027-03-31',
    subscriptionAmount: 450,
    financialYear: '2026-27',
    isActive: true,
  },
  {
    newspaperId: 103,
    name: 'Kurukshetra',
    publicationType: 'MAGAZINE',
    publisher: 'Ministry of Rural Development & MoIB',
    vendor: 'Government Publications Sales Depot',
    language: 'Hindi / English',
    frequency: 'Monthly',
    subscriptionFrom: '2026-01-01',
    subscriptionTo: '2026-12-31',
    subscriptionAmount: 450,
    financialYear: '2026-27',
    isActive: true,
  },
  {
    newspaperId: 104,
    name: 'Economic & Political Weekly (EPW)',
    publicationType: 'MAGAZINE',
    publisher: 'Sameeksha Trust',
    vendor: 'Academic Book & Periodicals Bureau',
    language: 'English',
    frequency: 'Weekly',
    subscriptionFrom: '2025-06-01',
    subscriptionTo: '2026-05-31',
    subscriptionAmount: 5800,
    financialYear: '2025-26',
    isActive: false, // EXPIRED
  },
  {
    newspaperId: 105,
    name: 'Down To Earth',
    publicationType: 'MAGAZINE',
    publisher: 'Centre for Science and Environment (CSE)',
    vendor: 'CSE Circulation Wing, New Delhi',
    language: 'English',
    frequency: 'Fortnightly',
    subscriptionFrom: '2026-01-01',
    subscriptionTo: '2026-12-31',
    subscriptionAmount: 1800,
    financialYear: '2026-27',
    isActive: true,
  },
];

// ─── DESIGNATION WISE BORROWING DURATION MASTER ───
export const STATIC_BORROWING_RULES: Library.DesignationBorrowRuleItem[] = [
  {
    ruleId: 1,
    designation: 'Advisor / Senior Director',
    maxBooksAllowed: 7,
    maxBooks: 7,
    borrowingDurationDays: 60,
    durationDays: 60,
    gracePeriodDays: 7,
    penaltyPerDay: 5,
    finePerDay: 5,
    description: 'Senior leadership & center advisors with extended research privileges',
    isActive: true,
  },
  {
    ruleId: 2,
    designation: 'Senior Research Fellow (SRF)',
    maxBooksAllowed: 5,
    maxBooks: 5,
    borrowingDurationDays: 45,
    durationDays: 45,
    gracePeriodDays: 5,
    penaltyPerDay: 5,
    finePerDay: 5,
    description: 'Senior research staff working on state policy papers',
    isActive: true,
  },
  {
    ruleId: 3,
    designation: 'Senior Consultant',
    maxBooksAllowed: 4,
    maxBooks: 4,
    borrowingDurationDays: 30,
    durationDays: 30,
    gracePeriodDays: 3,
    penaltyPerDay: 10,
    finePerDay: 10,
    description: 'Consultants and project subject matter experts',
    isActive: true,
  },
  {
    ruleId: 4,
    designation: 'Research Associate (RA)',
    maxBooksAllowed: 3,
    maxBooks: 3,
    borrowingDurationDays: 30,
    durationDays: 30,
    gracePeriodDays: 3,
    penaltyPerDay: 5,
    finePerDay: 5,
    description: 'General research fellows and data analysts',
    isActive: true,
  },
  {
    ruleId: 5,
    designation: 'Systems Analyst / IT Officer',
    maxBooksAllowed: 3,
    maxBooks: 3,
    borrowingDurationDays: 30,
    durationDays: 30,
    gracePeriodDays: 3,
    penaltyPerDay: 5,
    finePerDay: 5,
    description: 'Technical and systems administration personnel',
    isActive: true,
  },
  {
    ruleId: 6,
    designation: 'Documentation Officer / Section Head',
    maxBooksAllowed: 3,
    maxBooks: 3,
    borrowingDurationDays: 21,
    durationDays: 21,
    gracePeriodDays: 2,
    penaltyPerDay: 5,
    finePerDay: 5,
    description: 'Publications and administrative documentation officers',
    isActive: true,
  },
];

// ─── STATIC PROJECTS (AIGGPA – 9 Centers) ───
export const STATIC_PROJECTS: Library.ProjectItem[] = [
  {
    projectId: 1,
    projectName: 'CM Helpline Citizen Satisfaction & Redressal Audit',
    centerId: 1,
    centerName: 'Centre for Public Policy & Governance (CPPG)',
    advisor: 'Dr. R. K. Sharma',
    startYear: 2023,
    endYear: 2024,
    status: 'COMPLETED',
    description: 'Audit of the CM Helpline mechanism for citizen grievance redressal in MP',
    isActive: true,
  },
  {
    projectId: 2,
    projectName: 'E-Governance Policy Framework for MP Districts',
    centerId: 1,
    centerName: 'Centre for Public Policy & Governance (CPPG)',
    advisor: 'Dr. R. K. Sharma',
    startYear: 2024,
    status: 'ONGOING',
    description: 'Developing an e-governance blueprint for district-level administration in MP',
    isActive: true,
  },
  {
    projectId: 3,
    projectName: 'Smart Cities Mission: Urban Mobility & Infrastructure Index in MP',
    centerId: 2,
    centerName: 'Centre for Urban Governance (CUG)',
    advisor: 'Prof. Ananya Sen',
    startYear: 2022,
    endYear: 2023,
    status: 'COMPLETED',
    description: 'Study on urban mobility indicators and smart city infrastructure adoption in MP',
    isActive: true,
  },
  {
    projectId: 4,
    projectName: 'Urban Local Bodies Revenue Enhancement Study',
    centerId: 2,
    centerName: 'Centre for Urban Governance (CUG)',
    advisor: 'Prof. Ananya Sen',
    startYear: 2024,
    status: 'ONGOING',
    description: 'Research on own-revenue generation strategies for ULBs in Madhya Pradesh',
    isActive: true,
  },
  {
    projectId: 5,
    projectName: 'Panchayat Governance & Resource Mobilization Case Study',
    centerId: 3,
    centerName: 'Centre for Rural Development & Local Self Government (CRD)',
    advisor: 'Dr. Vivek Mishra',
    startYear: 2023,
    status: 'ONGOING',
    description: 'Comparative case study of gram panchayat governance in MP and Chhattisgarh',
    isActive: true,
  },
  {
    projectId: 6,
    projectName: 'AIGGPA Institutional Knowledge Repository Framework',
    centerId: 4,
    centerName: 'Centre for Knowledge Management (CKM)',
    advisor: 'Smt. Neeta Sharma',
    startYear: 2024,
    status: 'ONGOING',
    description: 'Building a structured KM system for AIGGPA institutional learning assets',
    isActive: true,
  },
  {
    projectId: 7,
    projectName: 'State Climate Action Plan: Forest & Water Body Conservation',
    centerId: 5,
    centerName: 'Centre for Climate Change & Environment (CCE)',
    advisor: 'Dr. Shweta Pathak',
    startYear: 2022,
    endYear: 2022,
    status: 'COMPLETED',
    description: 'Assessment and planning study for forest and water body conservation in MP',
    isActive: true,
  },
  {
    projectId: 8,
    projectName: 'Tribal Livelihood and Forest Rights Implementation Study in MP',
    centerId: 6,
    centerName: 'Centre for Social Development & Inclusive Growth (CSD)',
    advisor: 'Dr. Pradeep Nair',
    startYear: 2022,
    endYear: 2023,
    status: 'COMPLETED',
    description: 'Study on implementation of Forest Rights Act and its impact on tribal livelihoods',
    isActive: true,
  },
  {
    projectId: 9,
    projectName: 'Digital Financial Literacy Program for Rural MP',
    centerId: 7,
    centerName: 'Centre for Financial Management & Policy (CFM)',
    advisor: 'Shri Manoj Joshi',
    startYear: 2024,
    status: 'ONGOING',
    description: 'Developing financial literacy curriculum and delivery for rural communities',
    isActive: true,
  },
  {
    projectId: 10,
    projectName: 'AI Governance Readiness Assessment for MP Districts',
    centerId: 8,
    centerName: 'Centre for Innovation & Emerging Technologies (CIET)',
    advisor: 'Dr. Rajesh Patel',
    startYear: 2025,
    status: 'PROPOSED',
    description: 'Assessing AI adoption readiness across district administration in Madhya Pradesh',
    isActive: true,
  },
  {
    projectId: 11,
    projectName: 'Mission Karmayogi Competency Framework Rollout Study',
    centerId: 9,
    centerName: 'Centre for Human Resource & Capacity Building (CHRCB)',
    advisor: 'Dr. Meenakshi Tiwari',
    startYear: 2024,
    status: 'ONGOING',
    description: 'Study on rollout of Mission Karmayogi competency frameworks in MP civil services',
    isActive: true,
  },
];

