export const STATIC_BOOKS: Library.BookItem[] = [
  {
    bookId: 101,
    title: 'Good Governance: Delivering on Commitments',
    author: 'Bimal Jalan',
    publication: 'Rupa Publications',
    year: 2021,
    numberOfCopies: 12,
    availableCopies: 9,
    categoryId: 1,
    categoryName: 'Centers Collection (9 Centers)',
    categoryType: 'CENTER',
    centerId: 1,
    centerName: 'Centre for Public Policy & Governance (CPPG)',
    isbn: '978-8129135001',
    shelfLocation: 'Rack A1-04',
    isActive: true,
  },
  {
    bookId: 102,
    title: 'Urban Dynamics and Municipal Finance in India',
    author: 'Om Prakash Mathur',
    publication: 'Oxford University Press',
    year: 2020,
    numberOfCopies: 8,
    availableCopies: 6,
    categoryId: 1,
    categoryName: 'Centers Collection (9 Centers)',
    categoryType: 'CENTER',
    centerId: 2,
    centerName: 'Centre for Urban Governance (CUG)',
    isbn: '978-0199498214',
    shelfLocation: 'Rack B2-11',
    isActive: true,
  },
  {
    bookId: 103,
    title: 'Transforming Rural India: Policies and Outcomes',
    author: 'K. P. Kannan & M. S. Swaminathan',
    publication: 'Academic Foundation',
    year: 2019,
    numberOfCopies: 10,
    availableCopies: 7,
    categoryId: 1,
    categoryName: 'Centers Collection (9 Centers)',
    categoryType: 'CENTER',
    centerId: 3,
    centerName: 'Centre for Rural Development & Local Self Government (CRD)',
    isbn: '978-9332704503',
    shelfLocation: 'Rack C1-02',
    isActive: true,
  },
  {
    bookId: 104,
    title: 'Knowledge Management in Public Administration',
    author: 'David E. McNabb',
    publication: 'Routledge',
    year: 2022,
    numberOfCopies: 6,
    availableCopies: 5,
    categoryId: 1,
    categoryName: 'Centers Collection (9 Centers)',
    categoryType: 'CENTER',
    centerId: 4,
    centerName: 'Centre for Knowledge Management (CKM)',
    isbn: '978-0765619983',
    shelfLocation: 'Rack D3-08',
    isActive: true,
  },
  {
    bookId: 105,
    title: 'Climate Adaptation Strategies for Central India',
    author: 'Sunita Narain & J. Shukla',
    publication: 'CSE Books',
    year: 2023,
    numberOfCopies: 15,
    availableCopies: 11,
    categoryId: 1,
    categoryName: 'Centers Collection (9 Centers)',
    categoryType: 'CENTER',
    centerId: 5,
    centerName: 'Centre for Climate Change & Environment (CCE)',
    isbn: '978-8186906231',
    shelfLocation: 'Rack E1-05',
    isActive: true,
  },
  {
    bookId: 106,
    title: 'Wings of Fire: An Autobiography',
    author: 'Dr. A. P. J. Abdul Kalam',
    publication: 'Universities Press',
    year: 2018,
    numberOfCopies: 25,
    availableCopies: 18,
    categoryId: 3,
    categoryName: 'Auto-Biographies & Biographies',
    categoryType: 'AUTOBIOGRAPHY',
    isbn: '978-8173711466',
    shelfLocation: 'Rack G2-14',
    isActive: true,
  },
  {
    bookId: 107,
    title: 'The Story of My Experiments with Truth',
    author: 'Mahatma Gandhi',
    publication: 'Navajivan Publishing House',
    year: 2017,
    numberOfCopies: 30,
    availableCopies: 22,
    categoryId: 3,
    categoryName: 'Auto-Biographies & Biographies',
    categoryType: 'AUTOBIOGRAPHY',
    isbn: '978-8172290085',
    shelfLocation: 'Rack G2-15',
    isActive: true,
  },
  {
    bookId: 108,
    title: 'Atomic Habits: Tiny Changes, Remarkable Results',
    author: 'James Clear',
    publication: 'Random House Business Books',
    year: 2021,
    numberOfCopies: 20,
    availableCopies: 14,
    categoryId: 2,
    categoryName: 'Motivational Books',
    categoryType: 'MOTIVATIONAL',
    isbn: '978-1847941831',
    shelfLocation: 'Rack M1-01',
    isActive: true,
  },
  {
    bookId: 109,
    title: 'Leading with Soul and Wisdom',
    author: 'Lee G. Bolman & Terrence E. Deal',
    publication: 'Jossey-Bass',
    year: 2020,
    numberOfCopies: 14,
    availableCopies: 12,
    categoryId: 2,
    categoryName: 'Motivational Books',
    categoryType: 'MOTIVATIONAL',
    isbn: '978-0470619001',
    shelfLocation: 'Rack M1-05',
    isActive: true,
  },
  {
    bookId: 110,
    title: 'Public Financial Systems and Direct Benefit Transfers',
    author: 'R. Gopalan & M. C. Singhi',
    publication: 'Sage Publications',
    year: 2022,
    numberOfCopies: 9,
    availableCopies: 7,
    categoryId: 1,
    categoryName: 'Centers Collection (9 Centers)',
    categoryType: 'CENTER',
    centerId: 7,
    centerName: 'Centre for Financial Management & Policy (CFM)',
    isbn: '978-9354790119',
    shelfLocation: 'Rack F1-03',
    isActive: true,
  },
  {
    bookId: 111,
    title: 'AI and Digital Governance in Indian States',
    author: 'Nandan Nilekani & Tanuj Bhojwani',
    publication: 'Penguin Enterprise',
    year: 2023,
    numberOfCopies: 16,
    availableCopies: 10,
    categoryId: 1,
    categoryName: 'Centers Collection (9 Centers)',
    categoryType: 'CENTER',
    centerId: 8,
    centerName: 'Centre for Innovation & Emerging Technologies (CIET)',
    isbn: '978-0670097616',
    shelfLocation: 'Rack I2-09',
    isActive: true,
  },
  {
    bookId: 112,
    title: 'Capacity Building Framework for Civil Services',
    author: 'Mission Karmayogi Research Cell',
    publication: 'AIGGPA Press',
    year: 2024,
    numberOfCopies: 18,
    availableCopies: 15,
    categoryId: 1,
    categoryName: 'Centers Collection (9 Centers)',
    categoryType: 'CENTER',
    centerId: 9,
    centerName: 'Centre for Human Resource & Capacity Building (CHRCB)',
    isbn: '978-9380001099',
    shelfLocation: 'Rack H1-07',
    isActive: true,
  },
  {
    bookId: 113,
    title: 'CM Helpline Citizen Satisfaction & Redressal Audit Report',
    author: 'Dr. R. K. Sharma (Advisor)',
    publication: 'AIGGPA Publications',
    year: 2024,
    numberOfCopies: 15,
    availableCopies: 11,
    categoryId: 4,
    categoryName: 'AIGGPA Center Reports (9 Centers Table)',
    categoryType: 'AIGGPA_REPORT',
    centerId: 1,
    centerName: 'Centre for Public Policy & Governance (CPPG)',
    advisor: 'Dr. R. K. Sharma',
    shelfLocation: 'Report Section R1',
    isActive: true,
  },
  {
    bookId: 114,
    title: 'Madhya Pradesh Economic Survey 2023-24',
    author: 'Directorate of Economics and Statistics, MP',
    publication: 'Government of Madhya Pradesh',
    department: 'Directorate of Economics & Statistics, MP',
    year: 2024,
    numberOfCopies: 25,
    availableCopies: 21,
    categoryId: 5,
    categoryName: 'External Dept. Reports (Kisi Bahar ke Dept. Ki Report)',
    categoryType: 'GENERAL_REPORT',
    shelfLocation: 'Govt Whitepaper Section G4',
    isActive: true,
  },
];

export const STATIC_AIGGPA_REPORTS: Library.AiggpaReportItem[] = [
  {
    reportId: 201,
    centerId: 1,
    centerName: 'Centre for Public Policy & Governance (CPPG)',
    advisor: 'Dr. R. K. Sharma',
    projectName: 'CM Helpline Citizen Satisfaction & Redressal Audit Report',
    year: 2024,
    numberOfCopies: 15,
    availableCopies: 11,
    documentUrl: '/docs/reports/cm-helpline-2024.pdf',
    isActive: true,
  },
  {
    reportId: 202,
    centerId: 2,
    centerName: 'Centre for Urban Governance (CUG)',
    advisor: 'Prof. Ananya Sen',
    projectName: 'Smart Cities Mission: Urban Mobility & Infrastructure Index in MP',
    year: 2023,
    numberOfCopies: 10,
    availableCopies: 8,
    documentUrl: '/docs/reports/smart-cities-mp-2023.pdf',
    isActive: true,
  },
  {
    reportId: 203,
    centerId: 3,
    centerName: 'Centre for Rural Development & Local Self Government (CRD)',
    advisor: 'Dr. Vivek Mishra',
    projectName: 'Panchayat Governance & Resource Mobilization Case Study',
    year: 2023,
    numberOfCopies: 12,
    availableCopies: 9,
    documentUrl: '/docs/reports/panchayat-governance-2023.pdf',
    isActive: true,
  },
  {
    reportId: 204,
    centerId: 4,
    centerName: 'Centre for Knowledge Management (CKM)',
    advisor: 'Smt. Neeta Verma',
    projectName: 'AIGGPA Institutional Knowledge Repository Framework',
    year: 2024,
    numberOfCopies: 8,
    availableCopies: 7,
    documentUrl: '/docs/reports/ckm-framework-2024.pdf',
    isActive: true,
  },
  {
    reportId: 205,
    centerId: 5,
    centerName: 'Centre for Climate Change & Environment (CCE)',
    advisor: 'Dr. Shweta Pathak',
    projectName: 'State Climate Action Plan: Forest & Water Body Conservation',
    year: 2022,
    numberOfCopies: 14,
    availableCopies: 10,
    documentUrl: '/docs/reports/climate-action-2022.pdf',
    isActive: true,
  },
  {
    reportId: 206,
    centerId: 6,
    centerName: 'Centre for Social Development & Inclusive Growth (CSD)',
    advisor: 'Dr. Pradeep Nair',
    projectName: 'Tribal Livelihood and Forest Rights Implementation Study in MP',
    year: 2023,
    numberOfCopies: 12,
    availableCopies: 10,
    documentUrl: '/docs/reports/tribal-rights-2023.pdf',
    isActive: true,
  },
];

export const STATIC_GENERAL_REPORTS: Library.GeneralReportItem[] = [
  {
    reportId: 301,
    title: 'Madhya Pradesh Economic Survey 2023-24',
    year: 2024,
    numberOfCopies: 25,
    availableCopies: 21,
    author: 'Directorate of Economics and Statistics, MP',
    publisher: 'Government of Madhya Pradesh',
    isActive: true,
  },
  {
    reportId: 302,
    title: 'NITI Aayog Sustainable Development Goals (SDG) India Index 2023',
    year: 2023,
    numberOfCopies: 15,
    availableCopies: 12,
    author: 'NITI Aayog',
    publisher: 'Government of India',
    isActive: true,
  },
  {
    reportId: 303,
    title: 'National Family Health Survey (NFHS-5) MP State Report',
    year: 2022,
    numberOfCopies: 20,
    availableCopies: 17,
    author: 'Ministry of Health & Family Welfare',
    publisher: 'IIPS Mumbai',
    isActive: true,
  },
  {
    reportId: 304,
    title: 'Reserve Bank of India: State Finances Study of Budgets 2023',
    year: 2023,
    numberOfCopies: 10,
    availableCopies: 9,
    author: 'Department of Economic and Policy Research, RBI',
    publisher: 'RBI Publications',
    isActive: true,
  },
];

export const STATIC_BORROW_RECORDS: Library.BorrowItem[] = [
  {
    borrowId: 1,
    bookId: 101,
    bookTitle: 'Good Governance: Delivering on Commitments',
    borrowerName: 'Amitabh Srivastava',
    centerOrSection: 'Centre for Public Policy & Governance (CPPG)',
    designation: 'Research Associate',
    issueDate: '2026-09-01',
    dueDate: '2026-10-01',
    returnDate: null,
    status: 'ISSUED',
    reissueCount: 0,
    notes: 'For ongoing governance evaluation paper',
  },
  {
    borrowId: 2,
    bookId: 106,
    bookTitle: 'Wings of Fire: An Autobiography',
    borrowerName: 'Priyanka Sen',
    centerOrSection: 'Publications Section',
    designation: 'Documentation Officer',
    issueDate: '2026-08-15',
    dueDate: '2026-09-14',
    returnDate: null,
    status: 'OVERDUE',
    reissueCount: 0,
    notes: 'Reminder sent via email',
  },
  {
    borrowId: 3,
    bookId: 102,
    bookTitle: 'Urban Dynamics and Municipal Finance in India',
    borrowerName: 'Deepak Chawla',
    centerOrSection: 'Centre for Urban Governance (CUG)',
    designation: 'Senior Consultant',
    issueDate: '2026-08-20',
    dueDate: '2026-09-19',
    returnDate: null,
    status: 'OVERDUE',
    reissueCount: 1,
    notes: 'Reissued once on 19 Aug',
  },
  {
    borrowId: 4,
    bookId: 108,
    bookTitle: 'Atomic Habits: Tiny Changes, Remarkable Results',
    borrowerName: 'Rohit Agrawal',
    centerOrSection: 'Centre for Knowledge Management (CKM)',
    designation: 'Systems Analyst',
    issueDate: '2026-09-10',
    dueDate: '2026-10-10',
    returnDate: null,
    status: 'ISSUED',
    reissueCount: 0,
    notes: '',
  },
  {
    borrowId: 5,
    bookId: 105,
    bookTitle: 'Climate Adaptation Strategies for Central India',
    borrowerName: 'Dr. Sunita Baghel',
    centerOrSection: 'Centre for Climate Change & Environment (CCE)',
    designation: 'Research Fellow',
    issueDate: '2026-07-10',
    dueDate: '2026-08-09',
    returnDate: '2026-08-05',
    status: 'RETURNED',
    reissueCount: 0,
    notes: 'Returned in good condition',
  },
];
